name: calhacks
channels:
  - conda-forge
  - defaults
dependencies:
  # ─── Conda packages ──────────────────────────────────────────────
  - python=3.9
  - ffmpeg
  - cairo
  - numpy
  - scipy
  - pillow
  - networkx
  - moderngl
  - mapbox_earcut
  - cython
  - cffi
  - pyyaml
  - watchdog
  - dulwich
  - cachecontrol
  - filelock
  - click
  - poetry
  - pip           # make sure pip itself is available

  # ─── Pip-only packages ───────────────────────────────────────────
  - pip:
    - annotated-types==0.7.0
    - cachetools==5.5.0
    - google-ai-generativelanguage==0.6.10
    - google-api-core==2.21.0
    - google-api-python-client==2.149.0
    - google-auth==2.35.0
    - google-auth-httplib2==0.2.0
    - google-generativeai==0.8.3
    - googleapis-common-protos==1.65.0
    - grpcio==1.67.0
    - grpcio-status==1.67.0
    - httplib2==0.22.0
    - proto-plus==1.24.0
    - protobuf==5.28.2
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pyparsing==3.2.0
    - python-dotenv==1.0.1
    - rsa==4.9
    - uritemplate==4.1.1
